# Generated by Django 3.1.3 on 2020-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
