# Generated by Django 3.1.3 on 2020-12-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_announcement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Работа', 'Работа'), ('Електроника', 'Електроника'), ('Коли', 'Коли'), ('Дрехи', 'Дрехи'), ('За дома', 'За дома'), ('Подаръци', 'Подаръци'), ('Всички', 'Всички')], default='Всички', max_length=30),
        ),
    ]
